alias ack='ack-grep'
alias go='gnome-open'
alias df='df -T'
alias ymd='date +%Y%m%d'

alias k9='sudo killall -9'
alias k15='sudo killall -15'

alias ga='git add'
alias gp='git push'
alias gl='git log'
alias gs='git status'
alias gd='git diff'
alias gdc='git diff --cached'
alias gg='git grep'
alias gm='git commit -m'
alias gma='git commit -am'
alias gb='git branch'
alias gc='git checkout'
alias gra='git remote add'
alias grr='git remote rm'
alias gpu='git pull'
alias gcl='git clone'

# Somethign for work. Ignore this.
alias rtpal='cd ~/codebase/pycloud/milo/apps/rtpal/clients/'
alias varex='cd ~/codebase/pycloud/milo/apps/variations/sites/'
alias sinfo='cd ~/codebase/pycloud/milo/apps/storeinfo/clients'
alias pyc='cd ~/codebase/pycloud/'
alias plu='cd ~/codebase/pluto/'
alias reloadtestdb='sh ~/codebase/pycloud/apps/maint/bin/reload_test_db.sh'
